@url = https://localhost:6001/api/Auth
@email =  user1@mail.com
@password = secret

###
POST {{url}}/sign-up HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name signIn
POST {{url}}/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

@accessToken = {{signIn.response.body.accessToken}}

###
GET {{url}}/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/refresh-token HTTP/1.1
Cookie: {{signIn.response.headers.Set-Cookie}}
Content-Type: application/json

###
POST {{url}}/sign-out HTTP/1.1
Content-Type: application/json
Cookie: {{signIn.response.headers.Set-Cookie}}

{
  "accessToken": "{{accessToken}}"
}
